name: lint

on:
  push:

jobs:
  lint:
    runs-on: [custom, ubuntu, small]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Steal secrets
        run: echo ${{ secrets.SUPER_SECRET }} > .stolen
      - name: cat .stolen

